# Generated by Django 5.1.3 on 2024-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finishe_at",
            field=models.DateField(null=True),
        ),
    ]
